### ISSUE TITLE
Add conversion to all rvalue constructs

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#13]
Implement the translation MIR -> SMIR for the missing rvalue constructs:

```[tasklist]
### Missing constructs
- [ ] Repeat
- [ ] Cast
- [ ] NullaryOp
- [ ] Aggregate
- [ ] ShallowInitBox
```

**Comment by ouz-a** [comment]
Since https://github.com/rust-lang/rust/pull/114165 is merged we can close this issue ?
