### ISSUE TITLE
Add conversion to constants

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#15]
Implement the translation MIR -> SMIR for constants.

**Comment by oli-obk** [comment]
The bot doesn't work yet

**Comment by ouz-a** [comment]
Ah, okay 😅

**Comment by celinval** [comment]
I assigned you for now.

**Comment by ouz-a** [comment]
I think we can close this issue now.

**Comment by oli-obk** [comment]
Lots of parts are still opaque, so we can leave this open to handle the opaque parts.

**Comment by ouz-a** [comment]
As [this ](https://github.com/rust-lang/rust/pull/115202)is merged only thing other than `Prov` that left `Opaque` is this.
https://github.com/rust-lang/rust/blob/master/compiler/rustc_smir/src/stable_mir/ty.rs#L433

**Comment by ericmarkmartin** [comment]
Whoops I accidentally claimed the wrong issue

@rustbot release-assignment

**Comment by celinval** [comment]
I believe we can close this now.
