### ISSUE TITLE
Infrastructure: Add mechanism to validate SMIR

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#16]
We need a better mechanism to validate StableMIR translation. Maybe a mini-interpreter or at least create a debug option that we can inspect.

**Comment by oli-obk** [comment]
As a minimal first step we could create a dummy "codegen" that doesn't even monomorphize, but just tries to generate the MIR of all public items and all items needed by them.

**Comment by celinval** [comment]
@rustbot claim

Let's see if that works now.

**Comment by celinval** [comment]
Mechanism was added in #25
