### ISSUE TITLE
Do we need synchronous meetings?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/project-stable-mir#2]
Spawned off of https://github.com/rust-lang/project-stable-mir/pull/1#discussion_r871798992 

I started up an associated conversation on Zulip, here: https://rust-lang.zulipchat.com/#narrow/stream/320896-project-stable-mir/topic/meetings.3F.20meeting.20cadence.3F/near/282169329

(basically, the questions are: Do we want to have some sort of pre-determined meeting schedule? If so, what are its goals, who do we want to attend, and when+where is it held?)

If its too soon for us to have such meetings, then we can just close this. But I am wondering whether it will be good for some of our participants if we impose that structure.

**Comment by xldenis** [comment]
I feel like perhaps at the moment, _synchronous_ meetings may be premature, but  _(semi)-asynchronous_  meetings would be a good idea. I think it's important to keep track of the concurrent experiments and work going on. 

At the same time, I think there could be a lot of value gained by a synchronous _inaugural_ meeting, gather all the (currently) interested parties and set some concrete first goals.

**Comment by celinval** [comment]
I'm OK with having monthly meetings to keep things moving.

**Comment by spastorino** [comment]
Now that we have a bigger set of contributors, should we try to have bi-weekly meetings in order to keep things moving (as @celinval said)?.

cc @celinval @oli-obk @ouz-a @ericmarkmartin

**Comment by spastorino** [comment]
I think this can be now closed, we are organizing to meet on fridays https://rust-lang.zulipchat.com/#narrow/stream/320896-project-stable-mir/topic/Meeting.20agenda.3A.20Date.20TBD
