### ISSUE TITLE
Add ability to get a list of all trait impls

### ISSUE THREAD

**Issue by spastorino** [rust-lang/project-stable-mir#21]

**Comment by spastorino** [comment]
Done in https://github.com/rust-lang/rust/pull/114485/files

**Comment by spastorino** [comment]
Done in https://github.com/rust-lang/rust/pull/114599

**Comment by celinval** [comment]
@spastorino can we close this?

**Comment by spastorino** [comment]
Yes, implemented in https://github.com/rust-lang/rust/pull/114599
