### ISSUE TITLE
Handle Prov better

### ISSUE THREAD

**Issue by ouz-a** [rust-lang/project-stable-mir#22]
As of right now we cover Prov [here](https://github.com/rust-lang/rust/blob/9fa6bdd764a1f7bdf69eccceeace6d13f38cb2e1/compiler/rustc_smir/src/stable_mir/ty.rs#L259) by just making it `Opaque` and that is not very useful, instead we could handle them similar to how we handle `DefId` and would allow us to call [global_alloc](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.global_alloc) helping us to find out a lot of useful stuff.

**Comment by oli-obk** [comment]
> call [global_alloc](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.global_alloc) helping us to find out a lot of useful stuff.

We still need this in order to get a SMIR version of GlobalAlloc

**Comment by celinval** [comment]
I believe https://github.com/rust-lang/rust/pull/118012 covered the missing bit.
