### ISSUE TITLE
Improve handling of indexed types

### ISSUE THREAD

**Issue by ouz-a** [rust-lang/project-stable-mir#35]
Currently our implementation of indexed types such as `AllocId`, `DefId`, and soon https://github.com/rust-lang/rust/pull/115772 `Span` relies on https://github.com/rust-lang/rust/blob/master/compiler/rustc_smir/src/rustc_internal/mod.rs#L141-L154 this kind of brute way of doing things, this is fine for our small use cases but @oli-obk thinks and suggests this is going to be a problem in the future when we face real-world use cases where thousands of ids will be iterated, they suggest we should add a hasmap from value to index per table to improve our handling of these types.

**Comment by oli-obk** [comment]
Ideally, instead of duplicating that logic per type, we'd find something that provides this behaviour on crates.io or we write our own helper
