### ISSUE TITLE
Add support to `InstanceDef` and monomorphized `Instance`

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#36]
We should be able to create a stable version of  `Instance` since we now have GenericArgs. This will help us work with monomorphized code.

**Comment by oli-obk** [comment]
Where do we get it from? Or do you mean for creating manually and then getting the MIR for it?

**Comment by celinval** [comment]
> Where do we get it from? Or do you mean for creating manually and then getting the MIR for it?

Yes. I also think it's ok if for now we expose a conversion from internal to stable.
