### ISSUE TITLE
Add a conversion method for going from smir::Ty to rustc::Ty

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/project-stable-mir#46]
In order to be able to invoke some rustc operations (like `Instance::resolve`), we need the rustc version of `GenericArgs`, which contains `Ty`, `Lifetime` and `Const`. We should add functionality in the `rustc_smir` crate for converting back to these three rustc types when starting out with a smir type. This will mostly involve writing the inverse of their `Stable::stable` method.
```[tasklist]
### Tasks
- [ ] Implement `RustcInternal` for `Lifetime`
```

**Comment by celinval** [comment]
- `Ty` / `GenericArgs`: https://github.com/rust-lang/rust/pull/116964
- `Const`: https://github.com/rust-lang/rust/pull/117113

**Comment by celinval** [comment]
BTW, for `Lifetime`, we currently return `re_erased` which was added here: https://github.com/rust-lang/rust/pull/117688. However, we should implement a better mechanism without any loss of information.
