### ISSUE TITLE
Add an API to fetch the list of all reachable items of a crate

### ISSUE THREAD

**Issue by momvart** [rust-lang/project-stable-mir#64]
Following rust-lang/rust#121525, we can have the following method in `Context`.
```rust
fn reachable_items(&self, crate_num: CrateNum) -> Vec<DefId>;
```
It can be implemented by recursively traversing the crate using [`module_children`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/query/plumbing/struct.TyCtxtAt.html#method.module_children) (inefficient but easy to implement), or by introducing new queries in `TyCtxt` and `CrateMetadataRef` to flatten the list of all module items.

**Comment by celinval** [comment]
I was reading the issue you've linked, and I was wondering if adding a `pub fn fn_defs(&self) -> Vec<FnDef>` to `Crate` work for you? Or are you interested in a different type of definition?

I'm asking because I would also like an API like that. :)

**Comment by celinval** [comment]
BTW, we've been trying our best to avoid providing any APIs that expose DefId. We've been trying to provide APIs that are more specific for the DefId type. Thus, the methods we introduce are more suitable whatever type of definition is available, and this also means less error handling code.

Common functionalities for things that have a DefId are exposed by the `CrateDef` trait.

**Comment by momvart** [comment]
> I was wondering if adding a `pub fn fn_defs(&self) -> Vec<FnDef>` to `Crate` work for you?

Yeah, that makes sense to provide the functionality for `Crate`. I think I was thinking more about the compiler interface when I was writing the issue.

However,

> Or are you interested in a different type of definition?

I would like to have a general API. For example, static items might be useful as well. I'm not sure what range of `DefKind`s reachable items in other crates cover. Types, functions, and static items come to my mind. If the list goes on, we probably need to have a separate enum for reachable items.

**Comment by celinval** [comment]
I added support for static and function definitions. I have not created a generic function since DefId has no real functionality in stable mir. So it's not clear how useful it would be.

**Comment by momvart** [comment]
Thanks for the implementation.


> So it's not clear how useful it would be.

Yeah I think it's fine for now. It can be extended later if desired.
