### ISSUE TITLE
Can this also be perceived as an alternative to inline asm?

### ISSUE THREAD

**Issue by cher-nov** [rust-lang/project-stable-mir#90]
This is just a question. Such an analogy had already been drawn before: https://rust-lang.github.io/rfcs/2091-inline-semantic.html#inline-mir

Given that we're already have [`std::intrinsics::mir`](https://doc.rust-lang.org/1.82.0/std/intrinsics/mir/index.html) exposed, is it accurate to consider stable inline MIR as a **portable** (and thus better) alternative to inline assembly (`asm!` / `global_asm!`) in terms of more proximity to machine code and bare metal, as well as an expanded functionality that is inaccessible in the "main language"?

**Comment by bjorn3** [comment]
`std::intrinsics::mir` has nothing to do with stable MIR and will never be stable. Pretty much everything MIR can do can be done in the surface language of Rust. Most things that inline asm is often used for can't be done in either the surface language or MIR.
